### ISSUE TITLE
Menu not showing up

### ISSUE THREAD

**Issue by kluplau** [ogrosko/timber-clear-cache#2]
Hi,

The menu doesn't show up where it's intended. I've tried to uninstall and reinstall the plugin, and upgrade to latest Wordpress-version.

I'm running on localhost.

<img width="855" alt="skaermbillede 2016-05-07 kl 10 12 33" src="https://cloud.githubusercontent.com/assets/1536598/15091038/3eae19bc-143c-11e6-8b56-c396724874f8.png">

**Comment by ogrosko** [comment]
If you are running latest version 0.0.5 of plugin, button is hidden if timber cache is disabled. Make sure you have enabled Timber cache

**Comment by ogrosko** [comment]
Can be solved?
