### ISSUE TITLE
deprecated method

### ISSUE THREAD

**Issue by columbian-chris** [ogrosko/timber-clear-cache#3]
When I clear the cache with the button in the admin bar, it throws this error:

The Twig\Environment::clearCacheFiles method is deprecated since version 1.22 and will be removed in Twig 2.0.

**Comment by ogrosko** [comment]
Hello @columbian-chris 
I'm not maintaining this project, feel free to open PR. Or disabling WP_DEBUG should help (as quick fix) since it's just deprecation message

**Comment by columbian-chris** [comment]
@ogrosko Could we possibly push the 0.2.0 release to its home in the wordpress plugin directory?

**Comment by columbian-chris** [comment]
@ogrosko Thanks a lot for updating the plugin in the wordpress plugin directory. 🥇
